# Generated by Django 6.0.1 on 2026-08-26 12:19

import django.db.models.deletion
import djangocms_custom_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedServices',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('limit', models.PositiveIntegerField(default=3, verbose_name='Limit')),
            ],
            options={
                'verbose_name': 'Featured services',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(djangocms_custom_content.models.CustomGrouperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_custom_content_services.service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('title',),
            },
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTeaser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to='djangocms_custom_content_services.service')),
            ],
            options={
                'verbose_name': 'Service teaser',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
