# Generated by hand for the contrib example app.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Featured")),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="FeaturedServices",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("limit", models.PositiveIntegerField(default=3, verbose_name="Limit")),
            ],
            options={
                "verbose_name": "Featured services",
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="ServiceTeaser",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugins",
                        to="djangocms_custom_content_services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service teaser",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
