# Generated by Django 5.2.9 on 2026-02-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGrouper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Role')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_custom_content_people.persongrouper')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PersonTeaser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('show_bio', models.BooleanField(default=True, verbose_name='Show bio')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to='djangocms_custom_content_people.person')),
            ],
            options={
                'verbose_name': 'Person teaser',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
