# Generated by hand for the contrib example app.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("role", models.CharField(blank=True, max_length=200, verbose_name="Role")),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PersonTeaser",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("show_bio", models.BooleanField(default=True, verbose_name="Show bio")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugins",
                        to="djangocms_custom_content_people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person teaser",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
