# Generated by Django 5.2.9 on 2026-02-05 13:52

import django.db.models.deletion
import djangocms_custom_content.models
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(djangocms_custom_content.models.CustomGrouperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='role')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='mobile')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='fax')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_custom_content_people.person')),
                ('visual', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ('name',),
            },
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonTeaser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('show_bio', models.BooleanField(default=True, verbose_name='Show bio')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to='djangocms_custom_content_people.person')),
            ],
            options={
                'verbose_name': 'Person teaser',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
