# Generated by Django 6.0.1 on 2026-06-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_custom_content_people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonRelation',
        ),
    ]
