# Generated by Django 5.2.9 on 2026-02-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_custom_content_people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='person_grouper',
        ),
    ]
