# Generated by Django 6.0.5 on 2026-05-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_custom_content_people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonRelation',
        ),
    ]
