# Generated by hand for the contrib example app.

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "__first__"),
        ("djangocms_custom_content_categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("excerpt", models.TextField(blank=True, verbose_name="Excerpt")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Published at")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Featured")),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
                "ordering": ("-published_at",),
            },
        ),
        migrations.CreateModel(
            name="LatestBlogPosts",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("limit", models.PositiveIntegerField(default=5, verbose_name="Limit")),
                ("only_featured", models.BooleanField(default=False, verbose_name="Only featured")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djangocms_custom_content_categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Latest blog posts",
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BlogPostTeaser",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugins",
                        to="djangocms_custom_content_blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post teaser",
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="blog_posts", to="djangocms_custom_content_categories.category"),
        ),
    ]
