# Generated by Django 5.2.4 on 2026-02-04 13:58

import django.db.models.deletion
import django.utils.timezone
import djangocms_custom_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(djangocms_custom_content.models.CustomGrouperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('language', models.CharField(max_length=8, verbose_name='Language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_custom_content_blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ('-published_at',),
            },
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostTeaser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to='djangocms_custom_content_blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog post teaser',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
