# Generated by Django 6.0.5 on 2026-05-20 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djangocms_custom_content_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('relation_name', models.CharField(max_length=100, verbose_name='relation name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='djangocms_custom_content_blog.blogpost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
