# Generated by Django 6.0.1 on 2026-06-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djangocms_custom_content_blog', '0002_blogpostauthorsrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCategoriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='djangocms_custom_content_blog.blogpost')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='djangocms_c_content_9d064a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'content_type', 'object_id'), name='djangocms_custom_content_blog_blogpostcategoriesrelation_uniq')],
            },
        ),
    ]
