# Generated by Django 6.0.5 on 2026-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_custom_content_blog', '0002_blogpostcontentrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcontentrelation',
            options={'ordering': ('order', 'pk')},
        ),
        migrations.AddField(
            model_name='blogpostcontentrelation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
