# Generated by Django 6.0.1 on 2026-08-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
        ('djangocms_custom_content_blog', '0003_blogpostcategoriesrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('page_size', models.PositiveIntegerField(default=10, help_text='0 shows every post on one page.', verbose_name='Posts per page')),
                ('only_featured', models.BooleanField(default=False, verbose_name='Only featured')),
            ],
            options={
                'verbose_name': 'Blog post list',
                'verbose_name_plural': 'Blog post lists',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
