#
# djangocms-custom-content documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.

# fmt: off
import sys
from pathlib import Path

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
HERE = Path(__file__).parent
sys.path.insert(0, str(HERE.parent.parent))  # this way, we don't have to install the app

# Configure a minimal Django so autodoc can import the (concrete-model) modules.
# Trimmed compared to tests/test_settings: drops filer/easy_thumbnails and the
# contrib example apps, which the documented core modules do not need.
import django  # isort:skip  # noqa
from django.conf import settings  # isort:skip  # noqa

if not settings.configured:
    _INSTALLED_APPS = [
        "django.contrib.contenttypes",
        "django.contrib.auth",
        "django.contrib.sites",
        "django.contrib.sessions",
        "django.contrib.admin",
        "django.contrib.messages",
        "cms",
        "menus",
        "treebeard",
        "sekizai",
        "djangocms_custom_content",
    ]
    try:  # versioning is optional but documented modules import from it lazily
        import djangocms_versioning  # noqa

        _INSTALLED_APPS.append("djangocms_versioning")
    except ImportError:
        pass

    settings.configure(
        INSTALLED_APPS=_INSTALLED_APPS,
        DATABASES={"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}},
        MIDDLEWARE=[
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "cms.middleware.user.CurrentUserMiddleware",
            "cms.middleware.page.CurrentPageMiddleware",
            "cms.middleware.toolbar.ToolbarMiddleware",
            "cms.middleware.language.LanguageCookieMiddleware",
        ],
        TEMPLATES=[
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                        "sekizai.context_processors.sekizai",
                        "cms.context_processors.cms_settings",
                    ],
                },
            },
        ],
        CMS_TEMPLATES=(("page.html", "Page"),),
        CMS_CONFIRM_VERSION4=True,
        SITE_ID=1,
        SECRET_KEY="docs-build-key",
        DEFAULT_AUTO_FIELD="django.db.models.BigAutoField",
    )
    django.setup()

import djangocms_custom_content  # isort:skip  # noqa
# fmt: on


# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx_copybutton",
    "sphinxcontrib.spelling",
    "sphinx_design",
]

# Autodoc configuration
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "show-inheritance": True,
}
autodoc_typehints = "description"
autodoc_preserve_defaults = True
# Django/cms are configured and importable for real (see settings.configure
# above), so no autodoc_mock_imports are needed.


def autodoc_skip_member(app, what, name, obj, skip, options):
    """Skip Meta and Media classes from autodoc."""
    if name in {"Meta", "Media"}:
        return True
    return skip


def setup(app):
    app.connect("autodoc-skip-member", autodoc_skip_member)


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "djangocms-custom-content"
author = "Fabian Braun"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = djangocms_custom_content.__version__
# The full version, including alpha/beta/rc tags.
release = djangocms_custom_content.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

html_theme = "furo"
html_theme_options = {
    "navigation_with_keys": True,
}

# Output file base name for HTML help builder.
htmlhelp_basename = "djangocms-custom-contentdoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "djangocms-custom-content.tex",
        "djangocms-custom-content Documentation",
        author,
        "manual",
    ),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "djangocms-custom-content", "djangocms-custom-content Documentation", [author], 1)]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "djangocms-custom-content",
        "djangocms-custom-content Documentation",
        author,
        "djangocms-custom-content",
        "Custom content plugin for django CMS providing flexible template-based content blocks.",
        "Miscellaneous",
    ),
]

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
