# Generated by Django 5.2.9 on 2026-02-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FlatCategoryList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('only_featured', models.BooleanField(default=False, verbose_name='Only featured')),
                ('limit', models.PositiveIntegerField(default=0, help_text='0 = no limit', verbose_name='Limit')),
            ],
            options={
                'verbose_name': 'Category list',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FlatCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='djangocms_custom_content_categories.flatcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
