# Generated by hand for the contrib example app.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Featured")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="CategoryList",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("only_featured", models.BooleanField(default=False, verbose_name="Only featured")),
                ("limit", models.PositiveIntegerField(default=0, help_text="0 = no limit", verbose_name="Limit")),
            ],
            options={
                "verbose_name": "Category list",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
