# Generated by Django 6.0.5 on 2026-05-20 18:20

import django.db.models.deletion
import djangocms_custom_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(djangocms_custom_content.models.CustomGrouperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SampleGrouper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(djangocms_custom_content.models.CustomGrouperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StandaloneContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TagTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelTopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=5)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.reltopic')),
            ],
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelTopicContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('relation_name', models.CharField(max_length=100, verbose_name='relation name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='test_app.reltopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleGrouperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=5)),
                ('body', models.TextField(blank=True)),
                ('grouper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.samplegrouper')),
            ],
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StandaloneContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('relation_name', models.CharField(max_length=100, verbose_name='relation name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='test_app.standalonecontent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
