# Generated by Django 6.0.5 on 2026-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reltopiccontentrelation',
            options={'ordering': ('order', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='standalonecontentrelation',
            options={'ordering': ('order', 'pk')},
        ),
        migrations.AddField(
            model_name='reltopiccontentrelation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='standalonecontentrelation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
