# Generated by Django 6.0.1 on 2026-02-14 00:09

import django.db.models.deletion
import djangocms_custom_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGrouper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(djangocms_custom_content.models.CustomGrouperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SampleGrouperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=5)),
                ('body', models.TextField(blank=True)),
                ('grouper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.samplegrouper')),
            ],
            bases=(djangocms_custom_content.models.CustomContentMixin, models.Model),
        ),
    ]
