# Generated by Django 6.0.1 on 2026-06-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_samplegrouper_samplegroupercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrelation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bookrelation',
            name='instance',
        ),
        migrations.DeleteModel(
            name='AuthorRelation',
        ),
        migrations.DeleteModel(
            name='BookRelation',
        ),
    ]
