# Generated by Django 6.0.1 on 2026-06-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_bookrelation_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
